stages:
  - delivery

push-github:
  stage: delivery
  only:
    - main
    - tags
  before_script:
    - sudo apt install -y openssh-client
    - eval "$(ssh-agent -s)"
    - echo "$GITHUB_SSH_SECRET" | tr -d '\r' | ssh-add -
    - git config --local user.name "$GITHUB_USER"
    - git config --local user.email "$GITHUB_EMAIL"
    - git remote add github "$GITHUB_REMOTE_URL" || true
  script:
    - git branch main || git checkout main
    - git pull origin main -r
    - git push github main -f --tags
